//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormClient.RemoteDesktopProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteDesktopProxy.IRemoteDesktop", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IRemoteDesktop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteDesktop/UpdateScreenImage", ReplyAction="http://tempuri.org/IRemoteDesktop/UpdateScreenImageResponse")]
        byte[] UpdateScreenImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteDesktop/UpdateCursorImage", ReplyAction="http://tempuri.org/IRemoteDesktop/UpdateCursorImageResponse")]
        byte[] UpdateCursorImage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteDesktopChannel : WinFormClient.RemoteDesktopProxy.IRemoteDesktop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteDesktopClient : System.ServiceModel.ClientBase<WinFormClient.RemoteDesktopProxy.IRemoteDesktop>, WinFormClient.RemoteDesktopProxy.IRemoteDesktop {
        
        public RemoteDesktopClient() {
        }
        
        public RemoteDesktopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteDesktopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDesktopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDesktopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] UpdateScreenImage() {
            return base.Channel.UpdateScreenImage();
        }
        
        public byte[] UpdateCursorImage() {
            return base.Channel.UpdateCursorImage();
        }
    }
}
